dist: focal

language: c
os: linux

addons:
  apt:
    update: true
    packages:
      - nasm
      - libcurl4-openssl-dev
      - cmake
      - llvm-10
      - llvm-10-dev
      - clang-10
      - gcc
      - g++
env: 
  - CC=clang-10
    CXX=clang++-10

script: cmake --version && llvm-config --version && make && sudo make install && make smoketest
