dist: focal

addons:
  apt:
    update: true
    packages:
      - nasm
      - libcurl4-openssl-dev
      - cmake
      - llvm
      - llvm-dev
      - clang

script: make && sudo make install && make smoketest
