dist: focal

addons:
  apt:
    update: true
    packages:
      - nasm
      - libcurl4-openssl-dev
      - cmake
      - llvm
      - llvm-dev
      - clang-12
      - libclang-12-dev
      - gcc
      - g++

script: make && sudo make install && make smoketest
