dist: focal

language: c
os: linux

addons:
  apt:
    update: true
    packages:
      - nasm
      - libcurl4-openssl-dev
      - cmake
      - llvm
      - llvm-dev
      - clang-10
      - gcc
      - g++
env: 
  - CC=clang-10
    CXX=clang++-10

script: make && sudo make install && make smoketest
